services:
  - type: web
    name: pme-manager
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pme_manager.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
